name: weather
description: A Flutter application for weather.

version: 0.1.0+4

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  flutter:
    sdk: flutter

  cookie_jar: 1.0.1
  dio: ^3.0.8
  dio_cookie_manager: 1.0.0
  hive: ^1.3.0
  hive_flutter: ^0.3.0
  path_provider: ^1.5.1
  provider: ^4.0.0

dev_dependencies:
  build_runner: ^1.7.2
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/index/
    - assets/icons/weather/

  fonts:
    - family: "Lexend Exa"
      fonts:
        - asset: assets/fonts/lexend_exa.ttf
